# Generated by Django 2.2.16 on 2021-02-17 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rndt', '0001_initial')
    ]

    operations = [
        migrations.CreateModel(
            name='LayerRNDT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraints_other', models.TextField(default=None, null=True)),
                ('layer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='layers.Layer')),
            ],
            options={
                'verbose_name_plural': 'Layer RNDT',
                'ordering': ('layer', 'constraints_other'),
            },
        ),
    ]
