# Generated by Django 2.2.16 on 2021-02-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rndt', '0003_layerrndt'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerrndt',
            name='resolution',
            field=models.FloatField(default=None, null=True),
        ),
    ]
