# Generated by Django 2.2.16 on 2021-02-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rndt', '0004_layerrndt_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerrndt',
            name='accuracy',
            field=models.FloatField(default=None, null=True),
        ),
    ]
