# Generated by Django 4.2.23 on 2025-10-06 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rndt", "0007_migrate_metadata"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LayerRNDT",
        ),
    ]
